spring.application.name: pukapuka-service

spring:
  cloud:
    gateway:
      routes:
        - id: inoa
          uri: lb://inoa-service
          predicates:
            - Path=/inoa/**
          filters:
            - RewritePath=/inoa(?<segment>.*), $\{segment}
        - id: aloha
          uri: lb://aloha-service
          predicates:
            - Path=/aloha/**
          filters:
            - RewritePath=/aloha(?<segment>.*), $\{segment}


  sleuth:
    sampler:
      percentage: 0.0

# Logging
logging:
  pattern:
    console: "%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint}
          %clr([${spring.zipkin.service.name:${spring.application.name:-}},){magenta}%clr(%X{X-B3-TraceId:-},){yellow}%clr(%X{X-B3-SpanId:-},){cyan}%clr(,%X{X-Span-Export:-}]){blue}%clr([%8.15t]){cyan}
          %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n"