language: java
jdk: oraclejdk8

matrix:
  include:
    - name: "build foo-service"
      script:
        - cd foo-service
        - ./mvnw clean install -B
        - cd ..
    - name: "build bar-service"
      script:
        - cd bar-service
        - ./mvnw clean install -B
        - cd ..
    - name: "build foobar-service"
      script:
        - cd foobar-service
        - ./mvnw clean install -B
        - cd ..
