language: java
jdk: oraclejdk8

stages:
  - build aloha
  - build inoa
  - build punaewele
  - build pukapuka


jobs:
  include:
    - stage: build aloha
      script:
        - cd aloha-service
        - ./mvnw clean install -B
        - cd ..
    - stage: build inoa
        script:
          - cd inoa-service
          - ./mvnw clean install -B
          - cd ..
    - stage: build punaewele
        script:
          - cd punaewele-service
          - ./mvnw clean install -B
          - cd ..
    - stage: build pukapuka
        script:
          - cd pukapuka-service
          - ./mvnw clean install -B
          - cd ..

