language: java
jdk: oraclejdk8

matrix:
  include:
    - name: "build aloha"
      script:
        - cd aloha-service
        - ./mvnw clean install -B
        - cd ..
    - name: "build inoa"
      script:
        - cd inoa-service
        - ./mvnw clean install -B
        - cd ..
    - name: "build punaewele"
      script:
        - cd punaewele-service
        - ./mvnw clean install -B
        - cd ..
    - name: "build pukapuka"
      script:
        - cd pukapuka-service
        - ./mvnw clean install -B
        - cd ..