language: java
jdk: oraclejdk8

job:
  include:
    - stage: "build aloha-service"
      script:
        - cd aloha-service
        - ./mvnw clean install -B
        - cd ..
    - stage: "build inoa-service"
      script:
        - cd inoa-service
        - ./mvnw clean install -B
        - cd ..
    - stage: "build aggregate-service"
      script:
        - cd aggregate-service
        - ./mvnw clean install -B
        - cd ..
