language: java
jdk: oraclejdk8

matrix:
  include:
    - name: "build aloha-service"
      script:
        - cd aloha-service
        - ./mvnw clean install -B
        - cd ..
    - name: "build inoa-service"
      script:
        - cd inoa-service
        - ./mvnw clean install -B
        - cd ..
    - name: "build aggregate-service"
      script:
        - cd aggregate-service
        - ./mvnw clean install -B
        - cd ..
