defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: 'circleci/openjdk:8-jdk-browsers'



commands:
  sayhello:
    description: "A very simple command for demonstration purposes"
    parameters:
      to:
        type: string
        default: "Hello World"
    steps:
      - run: echo << parameters.to >>





version: 2.1
jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  build-maven:
    <<: *defaults

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - sayhello:
          to: "inoa-service"
      - run:
          name: maven build deploy
          command: |
            echo $INOA
            cd inoa-service
            mvn -s ../.circleci/settings.xml deploy
      - sayhello:
          to: "aloha-service"
      - run:
          name: maven build deploy
          command: |
            cd aloha-service
            mvn -s ../.circleci/settings.xml deploy
      - sayhello:
          to: "aggregate-service"
      - run:
          name: maven build deploy
          command: |
            cd aggregate-service
            mvn -s ../.circleci/settings.xml -DforkCount=0 deploy


workflows:
  version: 2.1
  build-and-release:
    jobs:
      - checkout_code
      - build-maven:
          requires:
            - checkout_code


#
#defaults: &defaults
#  working_directory: ~/repo
#  docker:
#    - image: 'circleci/openjdk:8-jdk-browsers'
#    working_directory: ~/repo
#    environment:
#      # Customize the JVM maximum heap limit
#      MAVEN_OPTS: -Xmx3200m