defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: 'circleci/openjdk:8-jdk-browsers'


commands:
  buildMavenModule:
    description: "Build and Deploy Maven Project"
    parameters:
      to:
        type: string
        default: "Please define a parameter"
    steps:
      - run:
          name: maven build deploy
          command: |
            cd << parameters.to >>
            mvn -s ../.circleci/settings.xml -DforkCount=0 deploy


version: 2.1
jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  build-maven:
    <<: *defaults

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - buildMavenModule:
          to: "inoa-service"
      - buildMavenModule:
          to: "aloha-service"
      - buildMavenModule:
          to: "aggregate-service"

workflows:
  version: 2.1
  build-and-release:
    jobs:
      - checkout_code
      - build-maven:
          requires:
            - checkout_code
