version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m
      INOA-SERVICE: "inoa-service"
      ALOHA-SERVICE: "aloha-service"
      AGGREGATE-SERVICE: "aggregate-service"
    steps:
      - checkout
      - run:
          name: maven build deploy ${INOA-SERVICE}
          command: |
            cd ${INOA-SERVICE}
            mvn -s ../.circleci/settings.xml deploy
      - run:
          name: maven build deploy ${ALOHA-SERVICE}
          command: |
            cd ${ALOHA-SERVICE}
            mvn -s ../.circleci/settings.xml deploy
      - run:
          name: maven build deploy ${AGGREGATE-SERVICE}
          command: |
            cd ${AGGREGATE-SERVICE}
            mvn -s ../.circleci/settings.xml -DforkCount=0 deploy


