defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: 'circleci/openjdk:8-jdk-browsers'


build-inoa: &build-inoa
  steps:
    - run:
        name: maven build deploy
        command: |
          echo $INOA
          cd inoa-service
          mvn -s ../.circleci/settings.xml deploy

version: 2
jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  build-maven:
    <<: *defaults

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      <<: *build-inoa
        -
#      - run:
#          name: maven build deploy
#          command: |
#            echo $INOA
#            cd inoa-service
#            mvn -s ../.circleci/settings.xml deploy
      - run:
          name: maven build deploy
          command: |
            cd aloha-service
            mvn -s ../.circleci/settings.xml deploy
      - run:
          name: maven build deploy
          command: |
            cd aggregate-service
            mvn -s ../.circleci/settings.xml -DforkCount=0 deploy


workflows:
  version: 2
  build-and-release:
    jobs:
      - checkout_code
      - build-maven:
          requires:
            - checkout_code


#
#defaults: &defaults
#  working_directory: ~/repo
#  docker:
#    - image: 'circleci/openjdk:8-jdk-browsers'
#    working_directory: ~/repo
#    environment:
#      # Customize the JVM maximum heap limit
#      MAVEN_OPTS: -Xmx3200m