# Checkout
checkout_and_cache: &checkout_and_cache
  steps:
    - checkout
    - persist_to_workspace:
        root: ~/repo
        paths:
          - .

# Default openJDK8
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: 'circleci/openjdk:8-jdk-browsers'
  environment:
    # Customize the JVM maximum heap limit
    MAVEN_OPTS: -Xmx3200m

# Build Command for Maven modules
commands:
  build-maven-module:
    description: "Build and Deploy Maven Project"
    parameters:
      to:
        type: string
        default: "Please define a parameter"
    steps:
      - run:
          name: maven build deploy
          command: |
            cd << parameters.to >>
            mvn -s ../.circleci/settings.xml -DforkCount=0 deploy

# Jobs
version: 2.1
jobs:
  checkout_code:
    <<: *defaults
    <<: *checkout_and_cache
  build-and-deploy:
    <<: *defaults
    # Steps
    steps:
      - checkout
      - build-maven-module:
          to: "foo-service"
      - build-maven-module:
          to: "customer-service"
      - build-maven-module:
          to: "foobar-service"

# Workflow
workflows:
  version: 2.1
  build_test_deploy:
    jobs:
      - build-and-deploy

