defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: 'circleci/openjdk:8-jdk-browsers'


version: 2
jobs:
  checkout_code:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  build-maven:
    <<: *defaults

    environment:
      # Customize the JVM maximum heap limit
      MAVEN_OPTS: -Xmx3200m

    steps:
      - checkout
      - run:
          name: maven build deploy ${INOA-SERVICE}
          command: |
            echo $INOA
            cd inoa-service
            mvn -s ../.circleci/settings.xml deploy
      - run:
          name: maven build deploy $ALOHA-SERVICE
          command: |
            cd aloha-service
            mvn -s ../.circleci/settings.xml deploy
      - run:
          name: maven build deploy $AGGREGATE-SERVICE
          command: |
            cd aggregate-service
            mvn -s ../.circleci/settings.xml -DforkCount=0 deploy


workflows:
  version: 2
  build-and-release:
    jobs:
      - checkout_code
      - build-maven:
          requires:
            - checkout_code


#
#defaults: &defaults
#  working_directory: ~/repo
#  docker:
#    - image: 'circleci/openjdk:8-jdk-browsers'
#    working_directory: ~/repo
#    environment:
#      # Customize the JVM maximum heap limit
#      MAVEN_OPTS: -Xmx3200m